--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'vending_machine_ttypes'

UpdateWeatherServiceClient = __TObject.new(__TClient, {
  __type = 'UpdateWeatherServiceClient'
})

function UpdateWeatherServiceClient:UpdateWeather(city, w)
  self:send_UpdateWeather(city, w)
  self:recv_UpdateWeather(city, w)
end

function UpdateWeatherServiceClient:send_UpdateWeather(city, w)
  self.oprot:writeMessageBegin('UpdateWeather', TMessageType.CALL, self._seqid)
  local args = UpdateWeather_args:new{}
  args.city = city
  args.w = w
  args:write(self.oprot)
  self.oprot:writeMessageEnd()
  self.oprot.trans:flush()
end

function UpdateWeatherServiceClient:recv_UpdateWeather(city, w)
  local fname, mtype, rseqid = self.iprot:readMessageBegin()
  if mtype == TMessageType.EXCEPTION then
    local x = TApplicationException:new{}
    x:read(self.iprot)
    self.iprot:readMessageEnd()
    error(x)
  end
  local result = UpdateWeather_result:new{}
  result:read(self.iprot)
  self.iprot:readMessageEnd()
end
UpdateWeatherServiceIface = __TObject:new{
  __type = 'UpdateWeatherServiceIface'
}


UpdateWeatherServiceProcessor = __TObject.new(__TProcessor
, {
 __type = 'UpdateWeatherServiceProcessor'
})

function UpdateWeatherServiceProcessor:process(iprot, oprot, server_ctx)
  local name, mtype, seqid = iprot:readMessageBegin()
  local func_name = 'process_' .. name
  if not self[func_name] or ttype(self[func_name]) ~= 'function' then
    if oprot ~= nil then
      iprot:skip(TType.STRUCT)
      iprot:readMessageEnd()
      x = TApplicationException:new{
        errorCode = TApplicationException.UNKNOWN_METHOD
      }
      oprot:writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x:write(oprot)
      oprot:writeMessageEnd()
      oprot.trans:flush()
    end
    return false, 'Unknown function '..name
  else
    return self[func_name](self, seqid, iprot, oprot, server_ctx)
  end
end

function UpdateWeatherServiceProcessor:process_UpdateWeather(seqid, iprot, oprot, server_ctx)
  local args = UpdateWeather_args:new{}
  local reply_type = TMessageType.REPLY
  args:read(iprot)
  iprot:readMessageEnd()
  local result = UpdateWeather_result:new{}
  local status, res = pcall(self.handler.UpdateWeather, self.handler, args.city, args.w)
  if not status then
    reply_type = TMessageType.EXCEPTION
    result = TApplicationException:new{message = res}
  else
    result.success = res
  end
  oprot:writeMessageBegin('UpdateWeather', reply_type, seqid)
  result:write(oprot)
  oprot:writeMessageEnd()
  oprot.trans:flush()
  return status, res
end

-- HELPER FUNCTIONS AND STRUCTURES

UpdateWeather_args = __TObject:new{
  city,
  w
}

function UpdateWeather_args:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I64 then
        self.city = iprot:readI64()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.I32 then
        self.w = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function UpdateWeather_args:write(oprot)
  oprot:writeStructBegin('UpdateWeather_args')
  if self.city ~= nil then
    oprot:writeFieldBegin('city', TType.I64, 1)
    oprot:writeI64(self.city)
    oprot:writeFieldEnd()
  end
  if self.w ~= nil then
    oprot:writeFieldBegin('w', TType.I32, 2)
    oprot:writeI32(self.w)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end

UpdateWeather_result = __TObject:new{

}

function UpdateWeather_result:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function UpdateWeather_result:write(oprot)
  oprot:writeStructBegin('UpdateWeather_result')
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end